services:
  web:
    container_name: vite-web
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"            # Vite dev server
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: >
      sh -lc "if [ ! -d node_modules ]; then npm ci; fi;
              npm run dev -- --host 0.0.0.0 --port 5173"
volumes:
  node_modules:
